import json
import os

from neo4j import GraphDatabase

from app.core.config import NEO4J_AUTH, NEO4J_URI

# --- 1. The "Menu" (Schema) ---
# This tells the LLM what tools are available.
TOOLS_SCHEMA = [
    {
        "type": "function",
        "function": {
            "name": "check_maturity_status",
            "description": "Reads the latest maturity analysis report. Returns a summary of PASS/FAIL status and violation counts. Always run this first.",
            "parameters": {
                "type": "object",
                "properties": {
                    "session_id": {
                        "type": "string",
                        "description": "The session ID to check (default to 'current' if unknown).",
                    }
                },
                "required": ["session_id"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "query_graph",
            "description": "Executes a read-only Cypher query against the Neo4j database. Use this to investigate specific elements or relationships when a rule fails.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The Cypher query to execute (e.g., MATCH (n) RETURN n LIMIT 5).",
                    }
                },
                "required": ["query"],
            },
        },
    },
]


# --- 2. The "Dispatcher" ---
# This routes the LLM's request to the actual Python function.
def execute_tool(name, args):
    if name == "check_maturity_status":
        return _get_maturity_summary(args.get("session_id"))

    elif name == "query_graph":
        return _run_cypher(args.get("query"))

    return f"Error: Tool '{name}' not found."


# --- 3. The "Workers" (Actual Logic) ---


def _get_maturity_summary(session_id):
    """Reads the evidence.json file generated by your analysis step."""
    evidence_file = "evidence.json"

    if not os.path.exists(evidence_file):
        return "No maturity evidence found. Please run the analysis first."

    try:
        with open(evidence_file, encoding="utf-8") as f:
            data = json.load(f)

        summary = f"Maturity Report (Session: {session_id})\n"
        results = data.get("results", [])

        if not results:
            return "The evidence file is empty."

        for res in results:
            status_icon = "✅" if res["status"] == "PASS" else "❌"
            count = res.get("violation_count", 0)
            summary += f"{status_icon} {res['rule_id']}: {res['status']} ({count} violations)\n"
            summary += f"   Rule: {res['description']}\n"

        return summary
    except Exception as e:
        return f"Error reading evidence file: {str(e)}"


def _run_cypher(query):
    """Runs a safe, read-only query against Neo4j."""
    # Security: Prevent the LLM from deleting your data
    forbidden = ["DELETE", "DETACH", "CREATE", "MERGE", "SET", "DROP"]
    if any(cmd in query.upper() for cmd in forbidden):
        return (
            "Error: This tool is Read-Only. specific mutation queries are not allowed."
        )

    try:
        with GraphDatabase.driver(NEO4J_URI, auth=NEO4J_AUTH) as driver:
            with driver.session() as session:
                result = session.run(query)
                # Convert Neo4j records to a clean list of dicts
                records = [r.data() for r in result]

                if not records:
                    return "No results found."

                # Limit response size so we don't crash the LLM context window
                if len(records) > 20:
                    return (
                        str(records[:20])
                        + f"\n... ({len(records) - 20} more records truncated)"
                    )

                return str(records)
    except Exception as e:
        return f"Cypher Execution Error: {str(e)}"
